package greeter

object fib {;import org.scalaide.worksheet.runtime.library.WorksheetSupport._; def main(args: Array[String])=$execute{;$skip(525); 

  //By considering the terms in the Fibonacci sequence whose values
  //do not exceed four million, find the sum of the even-valued terms.
  //Each new term in the Fibonacci sequence is generated by adding the previous two terms

  def fibValue(maxSum: Long): Long = {
    def loop(f: Long => Long)(prev: Long, current: Long, acc: Long): Long = {
      if (current > maxSum) acc else loop(f)(current, prev + current, acc + f(current))
    }

    loop(x => if (x % 2 == 0) x else 0)(0, 1, 0)
  };System.out.println("""fibValue: (maxSum: Long)Long""");$skip(33); val res$0 = 

  //4613732
  fibValue(4000000);System.out.println("""res0: Long = """ + $show(res$0))}
}
